// Generated by `node scripts/exportAbi.js` from the Hardhat artifacts + addresses.js.
import generated from "./generated.json";
import type { Abi } from "viem";

export const addresses = generated.addresses as {
  mUSD: `0x${string}`;
  mETH: `0x${string}`;
  amm: `0x${string}`;
  vault: `0x${string}`;
  platform: `0x${string}`;
  vaultDeployBlock?: number;
};

export const vaultAbi = generated.vaultAbi as Abi;
export const tokenAbi = generated.tokenAbi as Abi;
export const ammAbi = generated.ammAbi as Abi;

export const EXPLORER = "https://shannon-explorer.somnia.network";

// fixed-point (1e18) fraction → display percent
export const fmtPct = (fp: bigint | undefined) =>
  fp === undefined ? "—" : `${(Number(fp) / 1e16).toFixed(2)}%`;

export const fmtPrice = (p: bigint | undefined) =>
  p === undefined ? "—" : `$${(Number(p) / 1e8).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;

export const fmtToken = (v: bigint | undefined, digits = 2) =>
  v === undefined ? "—" : (Number(v) / 1e18).toLocaleString(undefined, { maximumFractionDigits: digits });
